### ISSUE TITLE
I did passwordless-nedbstore

### ISSUE THREAD

**Issue by zevero** [florianheinemann/passwordless-tokenstore#2]
Since I prefer [Nedb](https://github.com/louischatriot/nedb) over Mongodb for small projects (no setup etc) I rewrote your passwordless-mongostore and renamed it to

https://github.com/zevero/passwordless-nedbstore

It runs all the tests, but I had to cheat a little since nedb cant be closed and multiple instances on the same db file dont work well ... The hack is commented and will not hurt in practice.

Feel free to include it on https://passwordless.net/plugins

Thank you again for your efforts to get rid of those stupid passwords :)

**Comment by florianheinemann** [comment]
It's done! Thank you for the contribution!
Cheers
